Repository ArvinYang1925/kaiso-meow-backend, pull requests merged in 2025-06, with the labels that each got.

#74 Fix/sections response
  src/controllers/instructorSectionsController.ts
  src/test/testInstructorSectionController/batchCreateSections.api.test.ts
Labels: 優先權-高, Merge 後刪除分支

#78 feat: 🎸 issue API 編號31 提供講師姓名需求 #77
  src/controllers/instructorCourseController.ts
Labels: 優先權-高, Merge 後刪除分支, 前端需求

#76 Feature/sections reorder
  src/controllers/instructorSectionsController.ts
  src/routes/instructorRoutes.ts
  src/test/testInstructorSectionController/sortSections.api.test.ts
  src/validator/sectionVaildationsechema.ts
Labels: 優先權-高

#73 Feature/section video with simple queue
  package-lock.json
  package.json
  src/controllers/instructorVideoController.ts
  src/middleware/videoUpload.ts
  src/queues/processors/ffmpegHelpers.ts
  src/routes/instructorRoutes.ts
  src/services/videoTranscodeService.ts
  src/test/fixtures/sample.mp4
  src/test/testInstructorVideosController/getVideoStatus.api.test.ts
  src/test/testInstructorVideosController/uploadVideo.api.test.ts
  src/utils/firebaseUtils.ts
  src/utils/simpleQueue.ts
Labels: 優先權-中

#54 Feature/migration install
  package-lock.json
  package.json
  src/config/db.ts
  src/migrations/1748062120933-MakeCouponTypeNotNullable.ts
Labels: 需要兩人 Review, 優先權-中

#82 fix: 🐛 render deploy problem
  src/config/db.ts
Labels: 優先權-高, Merge 後刪除分支

#83 fix: 🐛 調整db.ts migration路徑
  src/config/db.ts
Labels: 優先權-高, Merge 後可先部署測試

#88 fix: 🐛 api15 調整回傳變數名稱
  src/controllers/orderController.ts
Labels: 優先權-高, Merge 後刪除分支

#86 Feature/delete video
  src/controllers/instructorVideoController.ts
  src/routes/instructorRoutes.ts
  src/test/testInstructorVideosController/deleteSectionVideo.api.test.ts
Labels: 優先權-高, Merge 後刪除分支

#89 docs: ✏️ add README
  README.md
Labels: 需要兩人 Review, 優先權-中, Merge 後刪除分支

#94 fix: 🐛 issue 72 & add checkCourseAccess middleware
  src/controllers/courseController.ts
  src/middleware/checkCourseAccess.ts
  src/middleware/isAuth.ts
  src/routes/courseRoutes.ts
Labels: Bug, 優先權-高, Merge 後刪除分支

#97 Feature/render notify
  .env.example
  src/server.ts
  src/utils/notifyDiscord.ts
Labels: 優先權-中, 兩人都可 Review 並 Merge, Merge 後刪除分支, Merge 後可先部署測試

#96 fix: 🐛 fix not to create coupon with same type
  src/controllers/instructorCouponController.ts
Labels: 優先權-中, Merge 後刪除分支, Merge 後可先部署測試

#101 chore: 🤖 add to set maximum numbers of generate sections
  src/controllers/instructorSectionsController.ts
Labels: 優先權-高, 兩人都可 Review 並 Merge, Merge 後刪除分支, Merge 後可先部署測試

#103 docs: ✏️ Readme 加上貢獻者與工作分配
  README.md
Labels: 優先權-中, Merge 後刪除分支

#105 fix: 🐛 講師收益課程選單 error code調整
  src/controllers/instructorController.ts
Labels: 優先權-高, Merge 後刪除分支, Merge 後可先部署測試
