Repository ArvinYang1925/kaiso-meow-backend, pull requests merged in 2025-05, with the labels that each got.

#12 Feature/userprofile
  src/controllers/authController.ts
  src/routes/authRoutes.ts
  src/validator/authValidationSchemas.ts
Labels: bug, 優先權-高

#11 chore: 🤖 建立所有sql tables
  src/entities/Coupon.ts
  src/entities/Course.ts
  src/entities/NewsletterSubscriber.ts
  src/entities/Order.ts
  src/entities/Section.ts
  src/entities/StudentProgress.ts
  src/entities/User.ts
Labels: 需要兩人 Review, 優先權-中

#19 feat: 🎸 improve register validation error messages
  src/validator/authValidationSchemas.ts
Labels: 優先權-高

#17 feat: 🎸 POST - /api/v1/newsletter/subscribe
  src/app.ts
  src/controllers/authController.ts
  src/controllers/newSletterController.ts
  src/middleware/optionalAuth.ts
  src/routes/newsletterRoutes.ts
  src/validator/authValidationSchemas.ts
Labels: 優先權-中

#18 feat: 🎸 (course) student get course list and detail
  src/app.ts
  src/controllers/courseController.ts
  src/routes/courseRoutes.ts
  src/validator/commonValidationSchemas.ts
Labels: 優先權-中

#21 Feature/GitHub template
  .github/pull_request_template/bug_fix.md
  .github/pull_request_template/chore.md
  .github/pull_request_template/docs_update.md
  .github/pull_request_template/feature.md
  .github/pull_request_template/hotfix.md
  .github/pull_request_template/refactor.md
  .github/pull_request_template/release.md
  .github/pull_request_template/security.md
  .github/pull_request_template/test_update.md
Labels: 需要兩人 Review, 優先權-中

#30 feat: 🎸 add comments and update structure in .env.example
  .env.example
Labels: 優先權-中, 兩人都可 Review 並 Merge, Merge 後刪除分支

#36 Feature/GitHub template
  .github/pull_request_template.md
  .github/workflows/gemini-pr-summary.yml
  scripts/generate-pr-summary.js
Labels: 需要兩人 Review

#37 Feature/instructor courses
  src/controllers/instructorCourseController.ts
  src/routes/instructorRoutes.ts
  src/validator/courseVaildationschema.ts
Labels: 優先權-中

#42 feat: 🎸 API No15.16
  src/controllers/orderController.ts
  src/routes/orderRoutes.ts
  src/utils/couponUtils.ts
Labels: 優先權-中, Merge 後刪除分支

#43 Feature/instructor coupons
  src/controllers/instructorCouponController.ts
  src/entities/Coupon.ts
  src/routes/instructorRoutes.ts
  src/validator/couponVaildationschema.ts
Labels: 優先權-高, Merge 後刪除分支

#39 feat: 🎸 add getInstructorOrders api
  src/controllers/instructorOrdersController.ts
  src/routes/instructorRoutes.ts
Labels: 優先權-中, Merge 後刪除分支

#35 Feature/student list
  src/controllers/instructorController.ts
  src/routes/instructorRoutes.ts
  src/validator/commonValidationSchemas.ts
Labels: 優先權-中, Merge 後刪除分支

#45 fix: 🐛 when error , return the result
  src/controllers/passwordController.ts
Labels: 優先權-高, Merge 後刪除分支

#44 feat: 🎸 API 17 18 綠界金流跳轉及call back
  .env.example
  package-lock.json
  package.json
  src/config/payment.ts
  src/controllers/orderController.ts
  src/routes/orderRoutes.ts
  tsconfig.json
  types/ecpay_aio_nodejs.d.ts
Labels: 優先權-中

#46 feat: 🎸 add getCourses & toggleCoursePublish APIs
  src/controllers/instructorCourseController.ts
  src/routes/instructorRoutes.ts
  src/validator/courseVaildationschema.ts
Labels: 優先權-中, Merge 後刪除分支

#38 Feature/jest install
  .env.test
  eslint.config.js
  jest.config.ts
  jest.setup.ts
  package-lock.json
  package.json
  src/app.ts
  src/controllers/instructorController.ts
  src/server.ts
  src/test/testInstructorController/getMe.api.test.ts
  src/utils/jwtUtils.ts
Labels: 需要兩人 Review, 優先權-低

#50 feat: 🎸 新增刪除課程 API
  src/controllers/instructorCourseController.ts
  src/routes/instructorRoutes.ts
Labels: 優先權-中

#51 Feature/instructor sections
  .gitignore
  src/controllers/instructorSectionsController.ts
  src/routes/instructorRoutes.ts
  src/test/testInstructorSectionController/createSectionByInstructor.api.test.ts
  src/test/testInstructorSectionController/deleteSection.api.test.ts
  src/test/testInstructorSectionController/getCourseSectionsByInstructor.api.test.ts
  src/test/testInstructorSectionController/publishSection.api.test.ts
  src/test/testInstructorSectionController/updateSection.api.test.ts
  src/utils/sectionUtils.ts
  src/validator/sectionVaildationsechema.ts
Labels: 需要兩人 Review, 優先權-中

#62 fix: 🐛 adjust order paidAt time zone
  src/controllers/orderController.ts
Labels: 小地方修改, Merge 後刪除分支

#66 Feature/ batchCreateSections by Instructor
  src/controllers/instructorSectionsController.ts
  src/routes/instructorRoutes.ts
  src/services/geminiService.ts
  src/services/openAIService.ts
  src/test/testInstructorSectionController/batchCreateSections.api.test.ts
  src/validator/sectionVaildationsechema.ts
Labels: Merge 後刪除分支

#70 refactor: 💡 issue_68 69
  src/controllers/orderController.ts
Labels: Merge 後刪除分支
